#!/usr/bin/env bash

# set colors
bspc config normal_border_color "#191716"
bspc config focused_border_color "#000000"

bspc config border_width 4
#bspc config top_padding 40
bspc config window_gap 8
bspc config split_ratio 0.5

# set monitors
bspc monitor eDP1 -d I II III IV
